[2025-07-22 17:55:10] Exception in speak_wx_conditions:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 3932, in speak_wx_conditions
    play_sequence(sequence, debug_log)
  File "/home/drx/DRX/drx_main.py", line 4673, in play_sequence
    found_wav = find_best_wav_for_words(words, EXTRA_SOUND_DIR)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drx/DRX/drx_main.py", line 4631, in find_best_wav_for_words
    for f in os.listdir(extra_dir):
             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/drx/DRX/sounds/extra'

[2025-07-22 17:55:05] Exception in speak_wx_conditions:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 3932, in speak_wx_conditions
    play_sequence(sequence, debug_log)
  File "/home/drx/DRX/drx_main.py", line 4673, in play_sequence
    found_wav = find_best_wav_for_words(words, EXTRA_SOUND_DIR)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drx/DRX/drx_main.py", line 4631, in find_best_wav_for_words
    for f in os.listdir(extra_dir):
             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/drx/DRX/sounds/extra'

[2025-07-22 17:54:59] Exception in speak_wx_conditions:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 3932, in speak_wx_conditions
    play_sequence(sequence, debug_log)
  File "/home/drx/DRX/drx_main.py", line 4673, in play_sequence
    found_wav = find_best_wav_for_words(words, EXTRA_SOUND_DIR)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drx/DRX/drx_main.py", line 4631, in find_best_wav_for_words
    for f in os.listdir(extra_dir):
             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/drx/DRX/sounds/extra'

